// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: process/grpc/logsrv.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogClient is the client API for Log service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogClient interface {
	ReadLog(ctx context.Context, in *LogDataSearchCondition, opts ...grpc.CallOption) (Log_ReadLogClient, error)
}

type logClient struct {
	cc grpc.ClientConnInterface
}

func NewLogClient(cc grpc.ClientConnInterface) LogClient {
	return &logClient{cc}
}

func (c *logClient) ReadLog(ctx context.Context, in *LogDataSearchCondition, opts ...grpc.CallOption) (Log_ReadLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &Log_ServiceDesc.Streams[0], "/grpc.log/readLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &logReadLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Log_ReadLogClient interface {
	Recv() (*LogData, error)
	grpc.ClientStream
}

type logReadLogClient struct {
	grpc.ClientStream
}

func (x *logReadLogClient) Recv() (*LogData, error) {
	m := new(LogData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogServer is the server API for Log service.
// All implementations must embed UnimplementedLogServer
// for forward compatibility
type LogServer interface {
	ReadLog(*LogDataSearchCondition, Log_ReadLogServer) error
	mustEmbedUnimplementedLogServer()
}

// UnimplementedLogServer must be embedded to have forward compatible implementations.
type UnimplementedLogServer struct {
}

func (UnimplementedLogServer) ReadLog(*LogDataSearchCondition, Log_ReadLogServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadLog not implemented")
}
func (UnimplementedLogServer) mustEmbedUnimplementedLogServer() {}

// UnsafeLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServer will
// result in compilation errors.
type UnsafeLogServer interface {
	mustEmbedUnimplementedLogServer()
}

func RegisterLogServer(s grpc.ServiceRegistrar, srv LogServer) {
	s.RegisterService(&Log_ServiceDesc, srv)
}

func _Log_ReadLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogDataSearchCondition)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogServer).ReadLog(m, &logReadLogServer{stream})
}

type Log_ReadLogServer interface {
	Send(*LogData) error
	grpc.ServerStream
}

type logReadLogServer struct {
	grpc.ServerStream
}

func (x *logReadLogServer) Send(m *LogData) error {
	return x.ServerStream.SendMsg(m)
}

// Log_ServiceDesc is the grpc.ServiceDesc for Log service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Log_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.log",
	HandlerType: (*LogServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "readLog",
			Handler:       _Log_ReadLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "process/grpc/logsrv.proto",
}
